### ISSUE TITLE
Error during execution of ./bootstrap_app.sh

### ISSUE THREAD

**Issue by shobhitg20** [IBM/SecuringArt-using-Blockchain-DigitalCertificates#10]
There's an error when i run the above script
throw new Error(errors.unsupportedEnvironment());
      ^

Error: imagesdoes not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/undefined/releases/tag/v3.0.1
    at module.exports (/Users/shobhit/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/images/scripts/util/binding.js:13:13)
    at Object.<anonymous> (/Users/shobhit/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/images/index.js:32:51)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous>

**Comment by asararatnakar** [comment]
Can you please provide the following details:

```
npm -v              
node -v
node -p process.versions
node -p process.platform
node -p process.arch
```

**Comment by shobhitg20** [comment]
npm -v   
6.4.1
node -v
v10.13.0
node -p process.versions
{ http_parser: '2.8.0',
  node: '10.13.0',
  v8: '6.8.275.32-node.36',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
node -p process.platform
node -p process.archdarwin
node -p process.arch
x64

**Comment by shobhitg20** [comment]
> Can you please provide the following details:
> 
> ```
> npm -v              
> node -v
> node -p process.versions
> node -p process.platform
> node -p process.arch
> ```

npm -v
6.4.1
node -v
v10.13.0
node -p process.versions
{ http_parser: '2.8.0',
node: '10.13.0',
v8: '6.8.275.32-node.36',
uv: '1.23.2',
zlib: '1.2.11',
ares: '1.14.0',
modules: '64',
nghttp2: '1.34.0',
napi: '3',
openssl: '1.1.0i',
icu: '62.1',
unicode: '11.0',
cldr: '33.1',
tz: '2018e' }
node -p process.platform
node -p process.archdarwin
node -p process.arch
x64
