### ISSUE TITLE
No authorisation token found?

### ISSUE THREAD

**Issue by pratiksharma1619** [IBM/SecuringArt-using-Blockchain-DigitalCertificates#6]
After typing **./bootstrap_app.sh** in the terminal and typing localhost:4000, and waiting for a while I am getting

UnauthorizedError: No authorization token was found
    at middleware (/Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/express-jwt/lib/index.js:76:21)
    at /Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/express-unless/index.js:47:5
    at Layer.handle [as handle_request] (/Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/express/lib/router/index.js:317:13)
    at /Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/pratiksunilsharma/Desktop/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/express/lib/router/index.js:317:13)

**Comment by ljbennett62** [comment]
@pratiksharma1619 - can you tell me about the system you are running your application on? What is the OS, and other configuration?  tx

**Comment by pratiksharma1619** [comment]
My OS is OSX and Node version is 8.9.3

**Comment by ljbennett62** [comment]
@gouravmodi @pratiksharma1619 - let me take a look- i am also working on a macos Sierra 10.13.3

**Comment by asararatnakar** [comment]
@pratiksharma1619 
That is the expected behaviour, for any operations to perform you would need to register a user first. Also  please refer [quicktest.sh](https://github.com/IBM/SecuringArt-using-Blockchain-DigitalCertificates/blob/master/quicktest.sh) for all the supported URLs.

When you say `typing localhost:4000` not working. I assumed you used the following command and that will not work as no endpoint defined for this

```
curl http://localhost:4000
```

**Comment by ljbennett62** [comment]
@pratiksharma1619 - now give it a try and close this issue if it works for you as instructed. tx

**Comment by ljbennett62** [comment]
@pratiksharma1619 @@gouravmodi - I just ran through the pattern with no issue - did you give it another try?  Remember to run the quicktest.sh to see the results
